version: '3.8'

services:
  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: prismedia-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=prismediadb
      - MYSQL_USER=prismedia
      - MYSQL_PASSWORD=securePassword
      - MYSQL_ROOT_PASSWORD=rootPassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prismedia-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  prismedia-network:
    driver: bridge

volumes:
  mysql-data:
