spring:
  application:
    name: prismedia-server-core
  profiles:
    active: local # 기본적으로 local 프로필 활성화
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, profile
  
server:
  port: 8080
  
logging:
  level:
    org.hibernate.SQL: debug
    com.prismedia: debug

# 애플리케이션 커스텀 속성
app:
  auth:
    token-secret: secret_key_must_change_in_production
    token-expiration-ms: 864000000 # 10일
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/redirect
    
# 로컬 환경 설정
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/prismediadb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: prismedia
    password: securePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# 배포 환경 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prismediadb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: prismedia
    password: securePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
